# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - nosetests